
project_id = "mgzfiouamidaqctnqnre"

[functions.analyze-bill]
verify_jwt = false

[[functions.analyze-bill.domains]]
domain = "*"
allowed_methods = ["GET", "POST", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization", "x-client-info", "apikey"]
exposed_headers = []
